apiVersion: v1
kind: Service // тип контроллера
metadata:
  name: first-service
spec:
  selector:
    app: my-web-app // селектор для поиска подов
  type: LoadBalancer 
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000 // обращаясь к Сервису по порту 3000 нас будет перенаправлять на порт 3000 Пода. 